version: '3.8'

services:
  api:
    container_name: rest_api
    image: rest_api:0.0.6
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
  mongo_db:
    container_name: rest_api_mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/db
    environment:
      - DB_NAME:rest_api

volumes:
  mongo_db: {}
